import BottomSheet from "./BottomSheet";
import Players from "./Players";
import Imposters from "./Imposters";
import TimeLimit from "./TimeLimit";
import Categories from "./Categories";
import Settings from "./Settings";
import Help from "./Help";
BottomSheet.Players = Players;
BottomSheet.Imposters = Imposters;
BottomSheet.TimeLimit = TimeLimit;
BottomSheet.Categories = Categories;
BottomSheet.Settings = Settings;
BottomSheet.Help = Help;
export default BottomSheet;
